version: 2.1
orbs:
  terraform: circleci/terraform@3.1.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - terraform/install:
          terraform_version: '1.2.8' 

workflows:
  example-workflow:
    jobs:
      - example-job
